### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by lou565** [haasome-tools/haasomeapi#3]
Haasomeapi Version: 3.2.0.1
Haasbot: BETA

Function call `get_all_trade_bots`:

TradebotApi.py -`_convert_json_bot_to_trade_bot_object` - `insurances[k] = safety `

UnboundLocalError: local variable 'safety' referenced before assignment.

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "bot.py", line 29, in bot_thread
    bots = haasclient.tradeBotApi.get_all_trade_bots()
  File "/usr/lib/python3.6/site-packages/haasomeapi/apis/TradeBotApi.py", line 91, in get_all_trade_bots
    bots.append(self._convert_json_bot_to_trade_bot_object(bot))
  File "/usr/lib/python3.6/site-packages/haasomeapi/apis/TradeBotApi.py", line 70, in _convert_json_bot_to_trade_bot_object
    insurances[k] = safety
UnboundLocalError: local variable 'safety' referenced before assignment

**Comment by lukosii** [comment]
Fix:
TradeBotApi.py

`insurance = super()._from_json(v, Insurance)

for insuranceoption in insurance.insuranceInterface:
      insuranceoptions.append(super()._from_json(insuranceoption, IndicatorOption))
      insurance.insuranceInterface = insuranceoptions
      insurances[k] = safety`

Replace `safety` with `insurance`

**Comment by R4stl1n** [comment]
Issue fixed in Merge Request #4 by lou565
